name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies
      run: dotnet restore
      working-directory: Project-03\Project-03Main\Project-03.sln

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: .\Project-03\Project-03Main\Project-03.sln

    - name: Test
      run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"
      working-directory: .\Project-03\Project-03Main\Project-03.sln

