name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
      working-directory: Project-04
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: Project-04
    - name: Test
      run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"
      working-directory: Project-04
    - name: Publish code coverage reports to codecove.io
      uses: codecov/codecov-action@v1
      with:
        token: efd05af3-65d1-4351-aa11-c5d6682a677b
        files: ./**/coverage.cobertura.xml
        fail_ci_if_error: true
